# vim:ft=ansible:
---
# This Playbook will install netdata

- name: git clone netdata
  git: repo=https://github.com/firehol/netdata.git depth=1 dest=/home/{{ user }}/netdata

- name: Get installation script 
  get_url: 
    url: 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' 
    dest: '/tmp/kickstart.sh' 

- name: Install dependencies 
  shell: echo 'Y' | bash /tmp/kickstart.sh netdata --dont-wait
  become: yes

- name: Install netdata 
  shell: ./netdata-installer.sh --dont-wait chdir=/home/{{ user }}/netdata/
  become: yes

- name: Register as a service
  shell: cp /home/{{ user }}/netdata/system/netdata-lsb /etc/init.d/netdata
  become: yes

- name: Makes it executable
  shell: chmod +x /etc/init.d/netdata
  become: yes

- name: Enable the service
  shell: update-rc.d netdata defaults
  become: yes

- name: Update Netdata configuration
  template: src=netdata.j2 dest=/etc/netdata/netdata.conf
  become: yes

- name: Run netdata
  shell: name=netdata state=started
  become: yes
